name: statistics-plugin-ci
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: yarn install
      - run: yarn test
      - run: yarn build

