name: statistics-plugin-ci
on: [push]
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: yarn install

  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: yarn test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: CultureHQ/actions-yarn@v1.0.1
      - run: yarn build

