name: release
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Integration test
        run: yarn test:integration
      - name: Release
        run: |
          git config --global user.name 'nemwiz'
          git config --global user.email 'nemwiz@users.no.reply.github.com'
          yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
